server:
  port: 8089
  tomcat:
    uri-encoding: utf-8

spring:
  application:
    name: fastjson_demo
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  profiles:
    active: dev
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/demo?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: 123456
#    hikari:
#      connection-timeout: 30000
#      auto-commit: true
#      max-lifetime: 1800000
#      pool-name: DatebookHikariCP
#      minimum-idle: 10
#      connection-test-query: SELECT 1
#      idle-timeout: 600000
#      maximum-pool-size: 20
#  jpa:
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        enable_lazy_load_no_trans: true
#    open-in-view: true
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true
#management:
#  server:
#    servlet:
#      context-path: /actuator
#  endpoints:
#    web:
#      exposure:
#        include: info, health,env
#  endpoint:
#    health:
#      show-details: always
#
#ribbon:
#  ReadTimeout: 60000
#  ConnectTimeout: 60000
#  MaxAutoRetries: 0
#  MaxAutoRetriesNextServer: 1
#  eureka:
#    enabled: true
#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: true
#        isolation:
#          thread:
#            timeoutInMilliseconds: 80000